### ISSUE TITLE
declaritive shadowroot inside an template

### ISSUE THREAD

**Issue by chris-kruining** [mfreed7/declarative-shadow-dom#13]
I am trying to implement this new feature for my SSR of component and loving it thus far. however, I've run into an issue, and I do hope I'm at the right place here.

what I'm struggling with is that for items I repeat (renderer with a for loop logic), those repeated items are stored in an template (normal template without `shadowroot` property), this template's content is then cloned and added to the DOM, just your typical client side rendering I can't get around due to dynamic data.

the problem for me now is that inside my template I have components with declared shadow-roots (`template[shadowroot="open"]`). These shadow-roots are however parsed immediately by the browser. Which causes me to loose the shadow-root when I clone the template's content.

Is the parsing of declaritive shadow-root inside templates by design? or an oversight perhaps?

I really hope that `template[shadowroot="open"]` inside `template`s could not be parsed immediately otherwise I can't use this feature at all and need to use normal templates and `attachShadow` by hand.

## Example
Ok, a couple of assumptions:
- the js knows about all these uuids.
- the js knows that the top-level template is used for the `inner[:for]`.
- I did not minimize the html to proof a point
- I transformed the inlined style to links in order to shrink the example

```html
        <unifyned-site-list items="{6b25cd26-067d-4470-ac4b-a7198036a0c2}">
            <template shadowroot="open">
                <link rel="stylesheet" href="https://fyncdn.nl/node_modules/@fyn-software/suite/css/style.css" />
                <link rel="stylesheet" href="/css/list.css" />
    
                <inner :for="{e323ebde-3423-4198-9825-6443ba509d91}"></inner>
            </template>
        </unifyned-site-list>

        <!-- Tile inner template (template outside of shadow used as template) -->
        <template id="d3f94231-bc96-4ac8-baf4-2436ce07340c">
            <unifyned-site-tile
                image="{30338a6f-6b2d-4caf-855a-d438d40f1936}"
                title="{8c294005-b118-485f-8385-bcc88ded568a}"
                score="{e2148814-acc9-44d3-b1d7-1b1a8bd32e7f}"
                favorited="{431edf7d-c590-4c1b-928f-6ba150413740}"
                cooked="{8f33137d-213e-4d12-a0ef-f10d0e637ae2}"
                recommendations="{5b53d3c4-a48e-449e-88ef-2de61dd0323f}"
            >
                <template shadowroot="open">
                    <link rel="stylesheet" href="https://fyncdn.nl/node_modules/@fyn-software/suite/css/style.css" />
                    <link rel="stylesheet" href="/css/tile.css" />
                    
                    <fyn-common-graphics-image src="{9a0c1945-8ebc-44ce-aa66-66c37ad57000}" alt="{cbc70811-b7d7-46af-9091-3a4f8d27745c}">
                        <template shadowroot="open">
                            <link rel="stylesheet" href="https://fyncdn.nl/node_modules/@fyn-software/suite/css/style.css" />
                            <link rel="stylesheet" href="https://fyncdn.nl/node_modules/@fyn-software/suite/css/common/graphics/image.css" />
                        
                            <slot></slot>
                        </template>
                    </fyn-common-graphics-image>
                
                    <main>
                        <h1>{cbc70811-b7d7-46af-9091-3a4f8d27745c}</h1>
                    
                        <counters>
                            <h2>{e4e6aed9-3be3-4f14-bfd4-d9bc38bf2332}</h2>
                            <p>Favorited</p>
                        
                            <h2>{39ca83c4-bb88-4489-9c11-a7f0767b3a41}</h2>
                            <p>Cooked</p>
                        </counters>
                    
                        <fyn-common-form-button primary>
                            <template shadowroot="open">
                                <link rel="stylesheet" href="https://fyncdn.nl/node_modules/@fyn-software/suite/css/style.css" />
                                <link rel="stylesheet" href="https://fyncdn.nl/node_modules/@fyn-software/suite/css/common/form/button.css" />
                                
                                <ripple><inner></inner></ripple>
    
                                <fyn-common-graphics-icon
                                    :if="{07dee2c2-ca29-4f78-95f5-fae640fee1d2}"
                                    icons="{ef6b2cd2-f5ba-4b75-8aeb-eebcc07db8b9}"
                                    type="{40a7b2b8-6e82-44e2-8d99-fc69dbf8f385}"
                                    main
                                    part="icon"
                                >
                                    <template shadowroot="open">
                                        <link rel="stylesheet" href="https://fyncdn.nl/node_modules/@fyn-software/suite/css/style.css" />
                                        <link rel="stylesheet" href="https://fyncdn.nl/node_modules/@fyn-software/suite/css/common/graphics/icon.css" />
                                        
                                        <inner class="fa-stack" :for="{007218e6-fd54-463b-af9b-93b7cb3b38e3}" part="stack"></inner>
    
                                        <slot></slot>
                                    </template>
                                </fyn-common-graphics-icon>
    
                                <slot part="content"></slot>
                            </template>
                        
                            See more recipes
                        </fyn-common-form-button>
                    
                        <footer :for="{507d8de0-fa1b-4018-90b2-6c0af9bac8cf}"></footer>
                    </main>
                </template>
            </unifyned-site-tile>
        </template>
    
        <!-- Tile's recommendations inner template (static template) -->
        <template id="f271f65f-1412-4c36-904d-404df1795728">
            <item>
                <fyn-common-graphics-image src="{3e0110a9-df0d-415a-80a4-073db3d31593}" insecure>
                    <template shadowroot="open">
                        <link rel="stylesheet" href="https://fyncdn.nl/node_modules/@fyn-software/suite/css/style.css" />
                        <link rel="stylesheet" href="https://fyncdn.nl/node_modules/@fyn-software/suite/css/common/graphics/image.css" />
                    
                        <slot></slot>
                    </template>
                </fyn-common-graphics-image>
            
                <h2>{612f3b6b-2130-42f2-b4ba-ea35381e6bca}</h2>
            
                <p>{8a0f0065-e5df-4057-aaf8-dcd1cddbf1fb}</p>
            </item>
        </template>
```

What I fiend must weird, surprising, and frustrating. that only the `fyn-common-form-button` of the first template and the `fyn-common-graphics-image` of the second template don't work. the `fyn-common-graphics-image` in the header of the first template does work as expected for some reason!

**Comment by mfreed7** [comment]
Thanks for raising this issue! So the TL/DR is that this should work as you expected. I'm not sure what's going on with your example, since you don't show the Javascript code to clone the templates. I tried it out [here in this Jsbin](https://jsbin.com/pesifik/edit?html,output), and it seems to work as expected. Let me know what you find not working there.

In general, the way the feature works is that "normal" templates that contain declarative shadow roots are parsed and attached within the template, as you mentioned. So the templates do contain attached shadow roots. But when you clone the template content, any contained shadow roots are also "copied" over to the clone. This is [discussed here in the explainer](https://github.com/mfreed7/declarative-shadow-dom#ordinary-templates-containing-declarative-shadow-dom).

Please see [this simple example Jsbin](https://jsbin.com/dekoxos/edit?html,output), which shows this working in practice. It contains this code:

```html
<body>
<template id=tmpl>
  <div>
    <template shadowroot=open>
      I am shadow content!
    </template>
    This light-dom child will not show up.
  </div>
</template>

<script>
  for(let i=0;i<10;++i) {
    document.body.appendChild(tmpl.content.cloneNode(true));
  }
</script>
```

Hopefully this helps! If you believe something about the above is not working correctly in Chromium, please [file a bug there](http://crbug.com/new) with sample code.

**Comment by chris-kruining** [comment]
it took me a while, but I managed to create a repro

https://jsfiddle.net/gnw4fdax/5/

as you can see in the console, when the documentFragment is cloned the nested shadowroot of the button element is ignored.

with some more experimentation it seems to be related to the `<main>` element. all shadowroots inside the `<main>` are not cloned.

is this by design? of a browser bug?

**Comment by mfreed7** [comment]
Thanks for the repro! That definitely looks like a browser/implementation bug. I've minimized your repro down to the one below, which shows the problem. The shadow root is not cloned if it is double-nested. I've [filed a bug against Chromium](https://crbug.com/1229311) and I'll take a look. Thanks!

The problem:
```html
<!DOCTYPE html>
<body>
<template id=tmpl>
  <div> <!-- Two nested elements are required here-->
    <div>
      <template shadowroot=open>This should be rendered.</template>
      This should NOT be rendered.
    </div>
  </div>
</template>

<div id=clone>This contains a clone:</div><br><br>
<div id=move>This contains a moved template:</div>

<script>
clone.appendChild(tmpl.content.cloneNode(true));
move.appendChild(tmpl.content);
</script>
```

**Comment by chris-kruining** [comment]
awesome, thank you for your efforts!

**Comment by chrishtr** [comment]
(For those following along: the Chromium bug was fixed.)

**Comment by chris-kruining** [comment]
@mfreed7 I don't think this is the right place to ask, but a new issue seemed overkill. 

Could it be that chrome has another issue regarding cloning? 
Elements that I clone that are/have been in the dom tree are cloned without their shadow-dom, be it open or closed. 

Is this correct behavior?

**Comment by reeceorbuck** [comment]
I found this old issue, while debugging a similar problem I am having. Maybe I'm misunderstanding, but each of your reproductions now seem to fail for me. 

I can see the content inside the template with shadowroot=open is cloned in the dev tools , but instead of displaying as #shadow-root, it is instead a #document-fragment and not actually rendering?

**Comment by mfreed7** [comment]
> I found this old issue, while debugging a similar problem I am having. Maybe I'm misunderstanding, but each of your reproductions now seem to fail for me.
> 
> I can see the content inside the template with shadowroot=open is cloned in the dev tools , but instead of displaying as #shadow-root, it is instead a #document-fragment and not actually rendering?

Likely better not to comment on old issues, but I'm guessing the problem with your example is that the attribute is called `shadowrootmode` in the final spec, and not `shadowroot`. Try `<div><template shadowrootmode=open>Hello</template></div>` which should work.

**Comment by reeceorbuck** [comment]
Sorry about that, I really appreciate the response. Since my previous post, I did notice that the spec had changed, which does alter the behavior somewhat. 

However, after correcting the attribute to shadowrootmode on your previous reproduction code (https://jsbin.com/wipequvevi/edit?html,output), I still do not see the shadow-root being included in the clone, no matter how it is nested. The result is I still see the light dom content in the template.

**Comment by mfreed7** [comment]
> Sorry about that, I really appreciate the response. Since my previous post, I did notice that the spec had changed, which does alter the behavior somewhat.
> 
> However, after correcting the attribute to shadowrootmode on your previous reproduction code (https://jsbin.com/wipequvevi/edit?html,output), I still do not see the shadow-root being included in the clone, no matter how it is nested. The result is I still see the light dom content in the template.

Sorry, I missed that you weren't using `shadowrootclonable`. See [this](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/template#shadowrootclonable). I.e. this works, in your repro:

`<template shadowrootmode=open shadowrootclonable>`

**Comment by reeceorbuck** [comment]
You're a legend, thank you so much!
 
Seems obvious now, but I had totally missed that property in all my searching around. 

Now it works as expected. Thanks for doing my tech support in an old closed issue comment thread.
